export const TEXT = {
  title: "Pawfront",
  gameControls: "Game controls",
  gameStatus: "Game status",
  stageProgress: "Stage progress",
  upgrades: "Upgrades",
  battlefield:
    "Battlefield. Move with WASD, arrow keys, or drag. Your cat fires automatically.",
  level: "Lv.",
  coinUnit: "cash",
  catUnit: "cat",
  to: "to",
  stage: "Stage",
  boss: "Boss",
  coins: "Cash",
  health: "Health",
  settings: "Settings",
  pause: "Pause",
  paused: "Paused",
  resume: "Resume",
  exit: "Exit",
  next: "Next",
  clearTrail: "Clear the trail",
  exitHint: "Follow the trail to the exit",
  cats: "Cats",
  choose: "Choose your cat",
  start: "Let’s go",
  close: "Close",
  damage: "Power",
  rate: "Speed",
  money: "Money",
  max: "MAX",
  upgrade: "Upgrade",
  perShot: "damage",
  perSecond: "shots / sec",
  multiplier: "cash earned",
  clear: "Stage clear!",
  defeat: "Back on your paws…",
  controls: "Follow the trail with WASD / arrows or drag",
  mute: "Mute sounds",
  motion: "Motion",
  system: "Use device setting",
  reduce: "Reduced",
  full: "Full",
  reset: "Reset progress",
  resetTitle: "Start over?",
  resetDescription:
    "Your cash, weapons, upgrades, and progress will be erased.",
  cancel: "Keep playing",
  saveUnavailable: "Saving unavailable. Progress lasts until this page closes.",
  loading: "Opening the trail…",
  loadError: "Artwork could not load.",
  retry: "Try again",
  weapon: "Equipped weapon",
  weapons: "Weapons",
  missions: "Missions",
  equip: "Equip",
  equipped: "Equipped",
  buyEquip: "Buy & equip",
  owned: "Owned",
  claim: "Claim",
  claimed: "Complete",
  missionReady: "Reward ready",
  missionHint: "Complete missions while you play. Claim cash here.",
  missionNames: {
    hunt: "Clear the trail",
    train: "Gear up",
    travel: "Keep moving",
  },
  missionUnits: {
    hunt: "enemies defeated",
    train: "upgrades bought",
    travel: "stages cleared",
  },
  weaponNotes: {
    wood: "Steady all-rounder",
    coral: "Heavy hits · slower fire",
    fish: "Fast fire · lighter hits",
  },
  catNames: { orange: "Orange", calico: "Calico", cream: "Cream" },
  weaponNames: {
    wood: "Wooden blaster",
    coral: "Coral blaster",
    fish: "Fish-can blaster",
  },
  biomes: ["Greenwood", "Sunstone", "Amberwood"],
};
